In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dayEvents = pd.read_csv('./dataset/World Important Dates.csv')

In [3]:
dayEvents.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,Unknown,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,Unknown,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,Unknown,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

## DayEvents Managing

1. แปลง Month และ Year ใน dayEvents

In [4]:
def formatYear(x):
    if 'BC' in x:
        return int(x.replace(' BC', '')) * -1
    return int(x)

In [5]:
monthMap = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

def formatMonth(x):
    if x in monthMap:
        return int(monthMap[x])
    else:
        return np.nan

In [6]:
dayEvents['Year'] = dayEvents['Year'].apply(formatYear).astype('Int64', errors='ignore')
dayEvents['Month'] = dayEvents['Month'].apply(formatMonth).astype('Int64', errors='ignore')
dayEvents.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,<NA>,-2600,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,<NA>,-1400,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,<NA>,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,4,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,5,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

2. Filter แค่ Year 1979-2021

In [7]:
filtered_dayEvents = dayEvents[(dayEvents['Year'] >= 1979) & (dayEvents['Year'] <= 2021)]

In [8]:
filtered_dayEvents.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
7,11,PokhranUnknownII Nuclear Tests,11,5,1998,India,Nuclear Test,Pokhran,India declared itself a nuclear state,International community,Atal Bihari Vajpayee,Mixed
8,12,Mumbai Terror Attacks,26,11,2008,India,Terrorism,Mumbai,Highlighted the threat of international terrorism,Citizens of Mumbai,LashkarUnknowneUnknownTaiba,Negative
14,18,Operation Blue Star,1,6,1984,India,Military Operation,Amritsar,Removal of armed militants from Golden Temple ...,Sikh community,"Indian Government, Sikh militants",Negative
15,19,Kargil War,Unknown,5,1999,India,Military Conflict,"Kargil, Ladakh",India regained control of Kargil; heightened p...,Indian Armed Forces,"Indian Government, Pakistani Military",Positive
16,20,Right to Information Act Enacted,15,6,2005,India,Legislation,India,Empowered citizens to seek information from pu...,Indian citizens,Government of India,Positive

In [9]:
filtered_dayEvents.info()

<class 'pandas.core.frame.DataFrame'>
Index: 389 entries, 7 to 1081
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              389 non-null    int64
 1   Name of Incident                    389 non-null    object
 2   Date                                389 non-null    object
 3   Month                               324 non-null    Int64
 4   Year                                389 non-null    Int64
 5   Country                             389 non-null    object
 6   Type of Event                       389 non-null    object
 7   Place Name                          389 non-null    object
 8   Impact                              389 non-null    object
 9   Affected Population                 389 non-null    object
 10  Important Person/Group Responsible  389 non-null    object
 11  Outcome                             389 non-null    object
dtypes: Int64(2), int64(1), object(9)
memory usage: 40.3+ KB

3. เติมค่าแค่สำหรับ Month ที่เป็น Null

In [10]:
null_month = filtered_dayEvents[ filtered_dayEvents['Month'].isnull()]

เอาชื่อให้ LLM ไป Search หาเดือน

In [11]:
null_month['Name of Incident'].to_csv('./dataset/null_month_events.csv', index=False)

In [12]:
# Data from research
month_mapping = {
    "Kargil Conflict": 5,
    "FATF Grey List": 6,
    "Siachen Glacier Conflict": 4,
    "Motorway Network Development": 11,
    "ChinaUnknownPakistan Friendship Highway Completion": 6,
    "Benazir Income Support Programme Launch": 7,
    "National Database and Registration Authority (NADRA) Establishment": 3,
    "HEC Digital Library Initiative": 2,
    "Sigiriya Designated as a UNESCO World Heritage Site": 12,
    "OneUnknownChild Policy Introduced": 9,
    "Deng Xiaoping's Southern Tour": 1,
    "Belt and Road Initiative Announced": 9,
    "SARS Epidemic": 2,
    "HighUnknownSpeed Rail Expansion": 4,
    "Made in China 2025 Initiative Announced": 5,
    "Australia Acts 1986": 3,
    "Royal Commission into Institutional Responses...": 1,
    "ANZUS Treaty Suspension": 9,
    "Rogernomics Initiatives Begin": 7,
    "Resource Management Act Enacted": 7,
    "1981 Springbok Tour Protests": 7,
    "Foreshore and Seabed Controversy": 5,
    "AntiUnknownNuclear Legislation Enacted": 6,
    "MMP Electoral System Introduced": 11,
    "New Zealand Signs Kyoto Protocol": 5,
    "1987 New Zealand Constitution Act": 12,
    "New Zealand Bill of Rights Act": 8,
    "Formation of the Māori Party": 7,
    "Recognition of the Māori Language": 8,
    "Decriminalization of Homosexuality": 7,
    "Kim DaeUnknownjung’s Sunshine Policy": 2,
    "THAAD Deployment Controversy": 7,
    "Kim JongUnknownun Assumes Power": 12,
    "Resolution on \"Vietnam's Marine Strategy to 2020\"": 10,
    "COVIDUnknown19 Pandemic Response": 1,
    "Speak Mandarin Campaign Launched": 9,
    "Capital Moved to Astana": 12,
    "1MDB Scandal": 7,
    "Release of Political Prisoners": 10,
    "Black Lives Matter Movement": 7,
    "USUnknownMexico Border Wall Expansion": 1,
    "#MeToo Movement": 10,
    "George Floyd Protests and Derek Chauvin Trial": 5,
    "Affordable Care Act (Obamacare) Implementation": 3,
    "Tech Boom and DotUnknowncom Bubble": 3,
    "Housing Market Crash and Great Recession": 12,
    "COVIDUnknown19 Pandemic in the UK": 1,
    "UK Hosts the First Rugby World Cup": 10,
    "Financial Crisis Impact": 9,
    "Austerity Measures During Crisis": 5,
    "Somali Civil War Begins": 1,
    "Movement for Multiparty Democracy": 7,
    "Land Reform Program Begins": 2,
    "Algerian Civil War Ends": 2,
    "Gacaca Courts Initiated": 6,
    "Joseph Kony Insurgency Declines": 7,
    "Boko Haram Insurgency Intensifies": 7,
    "Abolition of Slavery Enforced": 8,
    "Operation Carlota Ends": 5,
    "Direct Elections Now Campaign": 1,
    "Mensalão Scandal": 6,
    "Zika Virus Outbreak": 5,
    "Operation Car Wash (Lava Jato)": 3,
    "Refugee Crisis": 4,
    "Economic Crisis and IMF Loan": 4
}

In [13]:
null_month['Month'] = null_month['Name of Incident'].map(month_mapping)

C:\Users\User\AppData\Local\Temp\ipykernel_31736\217032279.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  null_month['Month'] = null_month['Name of Incident'].map(month_mapping)

In [14]:
null_month.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65 entries, 82 to 1078
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              65 non-null     int64
 1   Name of Incident                    65 non-null     object
 2   Date                                65 non-null     object
 3   Month                               65 non-null     int64
 4   Year                                65 non-null     Int64
 5   Country                             65 non-null     object
 6   Type of Event                       65 non-null     object
 7   Place Name                          65 non-null     object
 8   Impact                              65 non-null     object
 9   Affected Population                 65 non-null     object
 10  Important Person/Group Responsible  65 non-null     object
 11  Outcome                             65 non-null     object
dtypes: Int64(1), int64(2), object(9)
memory usage: 6.7+ KB

4. เอาค่าของ Month ที่แก้แล้วมารวมกับ Dataframe หลัก

In [15]:
filtered_dayEvents.update(null_month)

In [16]:
filtered_dayEvents.info()

<class 'pandas.core.frame.DataFrame'>
Index: 389 entries, 7 to 1081
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              389 non-null    int64
 1   Name of Incident                    389 non-null    object
 2   Date                                389 non-null    object
 3   Month                               389 non-null    Int64
 4   Year                                389 non-null    Int64
 5   Country                             389 non-null    object
 6   Type of Event                       389 non-null    object
 7   Place Name                          389 non-null    object
 8   Impact                              389 non-null    object
 9   Affected Population                 389 non-null    object
 10  Important Person/Group Responsible  389 non-null    object
 11  Outcome                             389 non-null    object
dtypes: Int64(2), int64(1), object(9)
memory usage: 40.3+ KB

In [17]:
filtered_dayEvents['Month'].unique()

<IntegerArray>
[5, 11, 6, 12, 8, 2, 7, 10, 1, 3, 9, 4]
Length: 12, dtype: Int64

5. เปลี่ยน column Date เป็น Day และแก้ค่าเป็น 1

In [18]:
filtered_dayEvents.rename(columns={'Date':'Day'}, inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_31736\2063186413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dayEvents.rename(columns={'Date':'Day'}, inplace=True)

In [19]:
filtered_dayEvents['Day'].unique()

array(['11', '26', '1', 'Unknown', '15', '16', '5', '3', '24', '13', '4',
       '9', '30', '31', '25', '8', '6', '22', '2', '14', '12', '18', '28',
       '27', '20', '10', '19', '29', '1998', '2004', '23', '21', '17',
       '7', '             ', 'March', '23Unknown25'], dtype=object)

In [20]:
filtered_dayEvents['Day'] = 1

C:\Users\User\AppData\Local\Temp\ipykernel_31736\1968262695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dayEvents['Day'] = 1

6. ทำ column Date เพิ่ม

In [21]:
filtered_dayEvents['Date'] = pd.to_datetime(
    dict(
        year=filtered_dayEvents['Year'],
        month=filtered_dayEvents['Month'],
        day=filtered_dayEvents['Day']
    ),
)

C:\Users\User\AppData\Local\Temp\ipykernel_31736\1293554916.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dayEvents['Date'] = pd.to_datetime(

In [22]:
filtered_dayEvents['Date']

7      1998-05-01
8      2008-11-01
14     1984-06-01
15     1999-05-01
16     2005-06-01
          ...
1076   2012-04-01
1078   2018-04-01
1079   2013-03-01
1080   2001-12-01
1081   2020-12-01
Name: Date, Length: 389, dtype: datetime64[ns]

In [23]:
filtered_dayEvents['Date'] = pd.to_datetime(filtered_dayEvents['Date'])
filtered_dayEvents.info()

<class 'pandas.core.frame.DataFrame'>
Index: 389 entries, 7 to 1081
Data columns (total 13 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              389 non-null    int64
 1   Name of Incident                    389 non-null    object
 2   Day                                 389 non-null    int64
 3   Month                               389 non-null    Int64
 4   Year                                389 non-null    Int64
 5   Country                             389 non-null    object
 6   Type of Event                       389 non-null    object
 7   Place Name                          389 non-null    object
 8   Impact                              389 non-null    object
 9   Affected Population                 389 non-null    object
 10  Important Person/Group Responsible  389 non-null    object
 11  Outcome                             389 non-null    object
 12  Date                                389 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(2), object(8)
memory usage: 43.3+ KB

C:\Users\User\AppData\Local\Temp\ipykernel_31736\3822671494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dayEvents['Date'] = pd.to_datetime(filtered_dayEvents['Date'])

In [24]:
filtered_dayEvents.head()

,Sl. No,Name of Incident,Day,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome,Date
7,11,PokhranUnknownII Nuclear Tests,1,5,1998,India,Nuclear Test,Pokhran,India declared itself a nuclear state,International community,Atal Bihari Vajpayee,Mixed,1998-05-01
8,12,Mumbai Terror Attacks,1,11,2008,India,Terrorism,Mumbai,Highlighted the threat of international terrorism,Citizens of Mumbai,LashkarUnknowneUnknownTaiba,Negative,2008-11-01
14,18,Operation Blue Star,1,6,1984,India,Military Operation,Amritsar,Removal of armed militants from Golden Temple ...,Sikh community,"Indian Government, Sikh militants",Negative,1984-06-01
15,19,Kargil War,1,5,1999,India,Military Conflict,"Kargil, Ladakh",India regained control of Kargil; heightened p...,Indian Armed Forces,"Indian Government, Pakistani Military",Positive,1999-05-01
16,20,Right to Information Act Enacted,1,6,2005,India,Legislation,India,Empowered citizens to seek information from pu...,Indian citizens,Government of India,Positive,2005-06-01

7. แบ่งประเภท Events

In [25]:
filtered_dayEvents.info()

<class 'pandas.core.frame.DataFrame'>
Index: 389 entries, 7 to 1081
Data columns (total 13 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              389 non-null    int64
 1   Name of Incident                    389 non-null    object
 2   Day                                 389 non-null    int64
 3   Month                               389 non-null    Int64
 4   Year                                389 non-null    Int64
 5   Country                             389 non-null    object
 6   Type of Event                       389 non-null    object
 7   Place Name                          389 non-null    object
 8   Impact                              389 non-null    object
 9   Affected Population                 389 non-null    object
 10  Important Person/Group Responsible  389 non-null    object
 11  Outcome                             389 non-null    object
 12  Date                                389 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(2), object(8)
memory usage: 43.3+ KB

In [26]:
mapping = {
    # === POLITICAL ===
    'Political': 'Political', 'Revolution': 'Political', 'Independence': 'Political',
    'Sovereignty Transition': 'Political', 'Political Change': 'Political',
    'Political Crisis': 'Political', 'Era Change': 'Political',
    'Political Milestone': 'Political', 'Political Development': 'Political',
    'Leadership Change': 'Political', 'Political Reform': 'Political',
    'Political Movement': 'Political', 'Coup': 'Political',
    'Cultural/Political': 'Political', 'Political Party': 'Political',
    'Political Corruption': 'Political', 'Government Agency': 'Political',
    'Political/Territorial Change': 'Political', 'Humanitarian/Political': 'Political',
    'Legal/Political': 'Political', 'Electoral Reform': 'Political',
    'Democratic Uprising': 'Political', 'Political Action': 'Political',
    'Electoral Victory': 'Political', 'General Election': 'Political',
    'Political/Infrastructure': 'Political', 'Political/Economic Integration': 'Political',
    'Political/Secession': 'Political', 'General Elections': 'Political',
    'Referendum': 'Political', 'Election': 'Political', 'Political Scandal': 'Political',
    'Corruption Scandal': 'Political', 'Corruption Investigation': 'Political',
    'AntiUnknownCorruption Effort': 'Political', 'Administrative': 'Political',
    'Administrative Change': 'Political', 'Regulatory Body': 'Political',
    'Population Control Policy': 'Political', 'Security Policy': 'Political',

    # === MILITARY & CONFLICT ===
    'Military Conflict': 'Military & Conflict', 'Military': 'Military & Conflict',
    'Military Operation': 'Military & Conflict', 'Military/Political': 'Military & Conflict',
    'Military Intervention': 'Military & Conflict', 'Civil War': 'Military & Conflict',
    'Ethnic Conflict': 'Military & Conflict', 'Regional Conflict': 'Military & Conflict',
    'Military Occupation': 'Military & Conflict', 'Genocide': 'Military & Conflict',
    'Rebellion': 'Military & Conflict', 'Insurgency': 'Military & Conflict',
    'Military Withdrawal': 'Military & Conflict', 'Conflict': 'Military & Conflict',
    'Rescue Operation': 'Military & Conflict',

    # === TERRORISM & VIOLENCE ===
    'Terrorism': 'Terrorism & Violence', 'Gun Violence': 'Terrorism & Violence',
    'Domestic Terrorism': 'Terrorism & Violence', 'Criminal Incident': 'Terrorism & Violence',
    'Security Incident': 'Terrorism & Violence', 'Judicial Execution': 'Terrorism & Violence',

    # === DIPLOMACY & INTERNATIONAL RELATIONS ===
    'International Agreement': 'Diplomacy & International Relations',
    'International Relations': 'Diplomacy & International Relations',
    'Diplomatic': 'Diplomacy & International Relations',
    'Peace Agreement': 'Diplomacy & International Relations',
    'Peace Process': 'Diplomacy & International Relations',
    'International Summit': 'Diplomacy & International Relations',
    'International Event': 'Diplomacy & International Relations',
    'International Cooperation': 'Diplomacy & International Relations',
    'Diplomatic/Religious': 'Diplomacy & International Relations',
    'International Finance': 'Diplomacy & International Relations',
    'International Recognition': 'Diplomacy & International Relations',
    'International Organization': 'Diplomacy & International Relations',
    'International Economic Integration': 'Diplomacy & International Relations',
    'International Exhibition': 'Diplomacy & International Relations',
    'International Economic Agreement': 'Diplomacy & International Relations',
    'International Incident': 'Diplomacy & International Relations',
    'Diplomatic Statement': 'Diplomacy & International Relations',
    'Diplomatic Agreement': 'Diplomacy & International Relations',
    'Diplomatic Policy': 'Diplomacy & International Relations',
    'International Integration': 'Diplomacy & International Relations',
    'International Trade Membership': 'Diplomacy & International Relations',
    'Diplomatic Incident': 'Diplomacy & International Relations',
    'Diplomatic Event': 'Diplomacy & International Relations',
    'International': 'Diplomacy & International Relations',
    'International Policy': 'Diplomacy & International Relations',
    'International Politics': 'Diplomacy & International Relations',
    'Historical Reconciliation': 'Diplomacy & International Relations',
    'Peace/Security': 'Diplomacy & International Relations',
    'World Expo': 'Diplomacy & International Relations',
    'Royal Event': 'Diplomacy & International Relations',

    # === ECONOMIC ===
    'Economic': 'Economic', 'Economic Policy': 'Economic',
    'Infrastructure': 'Economic', 'Economic Reform': 'Economic',
    'Environmental/Economic Policy': 'Economic', 'Financial Technology': 'Economic',
    'Economic/Infrastructure': 'Economic', 'Economic and Infrastructure Project': 'Economic',
    'Infrastructure Development': 'Economic', 'Economic Crisis': 'Economic',
    'Economic Integration': 'Economic', 'Economic/Social Reform Plan': 'Economic',
    'Land Reform': 'Economic',

    # === LEGAL & LEGISLATION ===
    'Legislation': 'Legal & Legislation', 'Legal': 'Legal & Legislation',
    'Legislative': 'Legal & Legislation', 'Legal Land Rights': 'Legal & Legislation',
    'Legal Framework': 'Legal & Legislation', 'Judiciary': 'Legal & Legislation',
    'Constitutional Amendment': 'Legal & Legislation',
    'Constitutional/Legal': 'Legal & Legislation',
    'Legal/Constitutional': 'Legal & Legislation', 'Legal/Social': 'Legal & Legislation',
    'Legal Inquiry': 'Legal & Legislation', 'Policy/Legislation': 'Legal & Legislation',
    'Environmental Legislation': 'Legal & Legislation',
    'Constitutional Reform': 'Legal & Legislation', 'Cultural/Legal': 'Legal & Legislation',
    'Legal Reform': 'Legal & Legislation', 'Judicial': 'Legal & Legislation',
    'Social Movement/Legal': 'Legal & Legislation', 'Justice System': 'Legal & Legislation',

    # === SOCIAL & CIVIL RIGHTS ===
    'Social Movement': 'Social & Civil Rights', 'Social Policy': 'Social & Civil Rights',
    'Social Unrest': 'Social & Civil Rights', 'Social Justice': 'Social & Civil Rights',
    'Civil Unrest': 'Social & Civil Rights', 'Protest Movement': 'Social & Civil Rights',
    'Protests': 'Social & Civil Rights', 'Social Welfare Program': 'Social & Civil Rights',
    'Human Rights Improvement': 'Social & Civil Rights', 'Social Reform': 'Social & Civil Rights',
    'Humanitarian': 'Social & Civil Rights',

    # === CULTURAL & RELIGIOUS ===
    'Cultural/Religious': 'Cultural & Religious', 'Cultural Heritage': 'Cultural & Religious',
    'Cultural Celebration': 'Cultural & Religious', 'Cultural Policy': 'Cultural & Religious',
    'Cultural Change': 'Cultural & Religious', 'Religious': 'Cultural & Religious',
    'Commemoration': 'Cultural & Religious', 'Historical': 'Cultural & Religious',
    'Environmental/Social': 'Cultural & Religious',

    # === NATURAL DISASTER ===
    'Natural Disaster': 'Natural Disaster', 'Disaster': 'Natural Disaster',
    'Maritime Disaster': 'Natural Disaster',

    # === ACCIDENT & INDUSTRIAL DISASTER ===
    'Aviation': 'Accident & Industrial Disaster',
    'Nuclear Accident': 'Accident & Industrial Disaster',
    'Maritime': 'Accident & Industrial Disaster',
    'Industrial Disaster': 'Accident & Industrial Disaster',
    'Accident': 'Accident & Industrial Disaster',
    'Structural Failure': 'Accident & Industrial Disaster',
    'Rail': 'Accident & Industrial Disaster',
    'Industrial Accident': 'Accident & Industrial Disaster',
    'Space Exploration Disaster': 'Accident & Industrial Disaster',

    # === NUCLEAR & WMD ===
    'Nuclear Test': 'Nuclear & WMD',

    # === HEALTH & PANDEMIC ===
    'Health': 'Health & Pandemic', 'Health Crisis': 'Health & Pandemic',
    'Public Health': 'Health & Pandemic', 'Healthcare': 'Health & Pandemic',

    # === SPORTS ===
    'International Sports Event': 'Sports', 'Sports': 'Sports',
    'Sporting Event': 'Sports', 'Sport': 'Sports',

    # === SCIENCE & TECHNOLOGY ===
    'Space Exploration': 'Science & Technology', 'Scientific': 'Science & Technology',
    'Telecommunications': 'Science & Technology',
    'Technological Advancement': 'Science & Technology',

    # === ENVIRONMENTAL ===
    'Environmental': 'Environmental', 'Wildlife Conservation': 'Environmental',
    'Environmental Policy': 'Environmental',

    # === EDUCATION ===
    'Education': 'Education',
}

filtered_dayEvents['Type of Event'] = filtered_dayEvents['Type of Event'].map(mapping)

C:\Users\User\AppData\Local\Temp\ipykernel_31736\1537966639.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dayEvents['Type of Event'] = filtered_dayEvents['Type of Event'].map(mapping)

In [27]:
filtered_dayEvents['Type of Event'].unique()

array(['Nuclear & WMD', 'Terrorism & Violence', 'Military & Conflict',
       'Legal & Legislation', 'Cultural & Religious', 'Economic',
       'Accident & Industrial Disaster', 'Political', 'Education',
       'Health & Pandemic', 'Sports', 'Natural Disaster',
       'Science & Technology', 'Environmental',
       'Diplomacy & International Relations', 'Social & Civil Rights'],
      dtype=object)

In [28]:
filtered_dayEvents['Type of Event'].value_counts()

Type of Event
Political                              103
Diplomacy & International Relations     45
Legal & Legislation                     40
Economic                                37
Military & Conflict                     31
Terrorism & Violence                    21
Social & Civil Rights                   21
Accident & Industrial Disaster          20
Sports                                  17
Natural Disaster                        16
Science & Technology                    10
Cultural & Religious                     9
Health & Pandemic                        8
Environmental                            5
Nuclear & WMD                            4
Education                                2
Name: count, dtype: int64

In [29]:
filtered_dayEvents.head()

,Sl. No,Name of Incident,Day,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome,Date
7,11,PokhranUnknownII Nuclear Tests,1,5,1998,India,Nuclear & WMD,Pokhran,India declared itself a nuclear state,International community,Atal Bihari Vajpayee,Mixed,1998-05-01
8,12,Mumbai Terror Attacks,1,11,2008,India,Terrorism & Violence,Mumbai,Highlighted the threat of international terrorism,Citizens of Mumbai,LashkarUnknowneUnknownTaiba,Negative,2008-11-01
14,18,Operation Blue Star,1,6,1984,India,Military & Conflict,Amritsar,Removal of armed militants from Golden Temple ...,Sikh community,"Indian Government, Sikh militants",Negative,1984-06-01
15,19,Kargil War,1,5,1999,India,Military & Conflict,"Kargil, Ladakh",India regained control of Kargil; heightened p...,Indian Armed Forces,"Indian Government, Pakistani Military",Positive,1999-05-01
16,20,Right to Information Act Enacted,1,6,2005,India,Legal & Legislation,India,Empowered citizens to seek information from pu...,Indian citizens,Government of India,Positive,2005-06-01

In [30]:
filtered_dayEvents.info()

<class 'pandas.core.frame.DataFrame'>
Index: 389 entries, 7 to 1081
Data columns (total 13 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              389 non-null    int64
 1   Name of Incident                    389 non-null    object
 2   Day                                 389 non-null    int64
 3   Month                               389 non-null    Int64
 4   Year                                389 non-null    Int64
 5   Country                             389 non-null    object
 6   Type of Event                       389 non-null    object
 7   Place Name                          389 non-null    object
 8   Impact                              389 non-null    object
 9   Affected Population                 389 non-null    object
 10  Important Person/Group Responsible  389 non-null    object
 11  Outcome                             389 non-null    object
 12  Date                                389 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(2), object(8)
memory usage: 43.3+ KB

8. check + ลบตัวซ้ำ

In [31]:
df = filtered_dayEvents.drop_duplicates(subset=['Name of Incident', 'Country', 'Year', 'Month'], keep='first')

9. Export CSV file

In [32]:
df.to_csv('./dataset/cleaned_dayEvents.csv', index=False)